### ISSUE TITLE
Erroneous results

### ISSUE THREAD

**Issue by botika** [djc/template-benchmarks-rs#22]
I keep a fork of this repository, https://github.com/botika/template-bench-rs. The benchmarks are released daily on travis, https://travis-ci.org/botika/template-bench-rs, and the results obtained are very different, in percentage, from those shown in the `README.md`. 

The last results at 21/11/2019
```
Big table/Askama        time:   [760.16 us 760.98 us 761.86 us]
Big table/fmt           time:   [388.87 us 399.50 us 409.52 us] // without escaping
Big table/fomat         time:   [359.47 us 360.05 us 360.69 us] // without escaping
Big table/Horrorshow    time:   [455.27 us 455.79 us 456.34 us]
Big table/Markup        time:   [362.50 us 362.81 us 363.13 us]
Big table/Yarte         time:   [360.53 us 361.11 us 361.75 us]
Big table/write         time:   [479.58 us 480.44 us 481.45 us] // without escaping

Teams/Askama            time:   [1.1994 us 1.2008 us 1.2023 us]
Teams/fmt               time:   [508.18 ns 528.53 ns 545.09 ns] // without escaping
Teams/fomat             time:   [630.17 ns 631.99 ns 635.08 ns] // without escaping
Teams/Horrorshow        time:   [712.72 ns 713.52 ns 714.37 ns]
Teams/Markup            time:   [542.14 ns 542.87 ns 543.75 ns]
Teams/Yarte             time:   [474.83 ns 475.49 ns 476.22 ns]
Teams/write             time:   [877.54 ns 879.11 ns 881.06 ns] // without escaping
```

It can lead to a mistake in less experienced developers

**Comment by djc** [comment]
I don't know why that happens. I'm generally a bit suspicious of results from CI environments because a lot could potentially be going on in such an environment. There's probably also differences between server CPUs and the laptop CPU my benchmark runs on.

In general, this repository just provides one set of benchmarks. I've tried to make them fair but I'm not sure what causes your results to diverge from mine, so I don't know how I correct them.

**Comment by botika** [comment]
I understand that the result between one processor and another is different. 
Well, I don't know what could be happening since I don't know on what computer, with how many processes or nothing of how they have been launched. 
But the result that shows both my i7-7700HQ and travis vcore are the same in percentage. 

You can launch them on an instance of a dedicated server, but rely on the stability of a vcore, and display the logs. Or warn that the results are merely indicative and may vary. Or not show the results and invite everyone to launch them on their machines. 
Surely there are many more better options than showing erroneous results.

**Comment by djc** [comment]
I've added some details and a warning in 12ffa15. I did notice your repository does not display any warnings and does display results, so that makes this bug somewhat hypocritical IMO.

**Comment by botika** [comment]
I do not put any result just the report from travis and I hope that the developers are smart enough to draw their own conclusions.
Well man, keep cheating people, in the end in your code there are very serious structural problems and you know it. Fearing the results you do not win anything, you just have to launch it on any computer to know the truth.

**Comment by mbrubeck** [comment]
Apparently the divergence is because the results were last updated before PR #21 was merged. Re-running the benchmarks on current `master` should fix this.

**Comment by djc** [comment]
I've pushed updated results today. I've done them on a server because I was wondering if the results were being influenced by thermal throttling from my laptop. A server should also (a) be more reflective to the actual production environment for many of these things, and (b) more similar to a Travis vcore. However, I still see yarte at roughly 2x Askama performance.
